<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <groupId>top.tangyh.basic</groupId>
    <artifactId>lamp-bom</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <modelVersion>4.0.0</modelVersion>
    <name>${project.artifactId}</name>
    <description>管理lamp-util项目子模块的依赖</description>
    <url>https://github.com/zuihou/lamp-cloud</url>

    <properties>
        <revision>5.10.0</revision>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- FastDFS文件 -->
            <dependency>
                <groupId>top.tangyh.basic</groupId>
                <artifactId>fastdfs-client</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>top.tangyh.basic</groupId>
                <artifactId>lamp-all-cloud</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>top.tangyh.basic</groupId>
                <artifactId>lamp-all-boot</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>top.tangyh.basic</groupId>
                <artifactId>lamp-annotation</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>top.tangyh.basic</groupId>
                <artifactId>lamp-webmvc</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>top.tangyh.basic</groupId>
                <artifactId>lamp-cache-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>top.tangyh.basic</groupId>
                <artifactId>lamp-captcha-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>top.tangyh.basic</groupId>
                <artifactId>lamp-cloud-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>top.tangyh.basic</groupId>
                <artifactId>lamp-core</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>top.tangyh.basic</groupId>
                <artifactId>lamp-databases</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>top.tangyh.basic</groupId>
                <artifactId>lamp-echo-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>top.tangyh.basic</groupId>
                <artifactId>lamp-log-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>top.tangyh.basic</groupId>
                <artifactId>lamp-mq-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>top.tangyh.basic</groupId>
                <artifactId>lamp-mvc</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>top.tangyh.basic</groupId>
                <artifactId>lamp-scan-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>top.tangyh.basic</groupId>
                <artifactId>sop-service-support</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>top.tangyh.basic</groupId>
                <artifactId>sop-spring-boot-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>top.tangyh.basic</groupId>
                <artifactId>lamp-swagger2-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>top.tangyh.basic</groupId>
                <artifactId>lamp-uid</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>top.tangyh.basic</groupId>
                <artifactId>lamp-validator-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>top.tangyh.basic</groupId>
                <artifactId>lamp-xss-starter</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <licenses>
        <license>
            <name>Apache 2</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
            <comments>A business-friendly OSS license</comments>
        </license>
    </licenses>
    <developers>
        <developer>
            <id>zuihou</id>
            <name>zuihou</name>
            <email>306479353@qq.com</email>
            <roles>
                <role>Java Development Engineer</role>
            </roles>
            <timezone>2020-03-12 17:50:10</timezone>
        </developer>
    </developers>
    <scm>
        <connection>scm:git@github.com:zuihou/lamp-util.git</connection>
        <developerConnection>scm:git@github.com:zuihou/lamp-util.git</developerConnection>
        <url>git@github.com:zuihou/lamp-util.git</url>
    </scm>

    <profiles>
        <profile>
            <!-- 打包的 -P参数 -->
            <id>release</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <version>0.4.0</version>
                        <extensions>true</extensions>
                        <configuration>
                            <publishingServerId>oss</publishingServerId>
                            <tokenAuth>true</tokenAuth>
                        </configuration>
                    </plugin>
                    <!-- GPG  打包插件-->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>1.6</version>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
        </profile>
    </profiles>
</project>
